// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdETmIU8BGxjUMvveAkXErVSWXLP1AEwQ',
    appId: '1:558386649713:web:f28c694375a9729d51d9d0',
    messagingSenderId: '558386649713',
    projectId: 'flutter-fb-auth-4fdc1',
    authDomain: 'flutter-fb-auth-4fdc1.firebaseapp.com',
    storageBucket: 'flutter-fb-auth-4fdc1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe3u_DAbA2mcMKJn9W8UWQ6G4nLkW9HrE',
    appId: '1:558386649713:android:fbe97c4b03a7f65851d9d0',
    messagingSenderId: '558386649713',
    projectId: 'flutter-fb-auth-4fdc1',
    storageBucket: 'flutter-fb-auth-4fdc1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYZRYEFfk34PxQ_rCj5gW8MPIRRWjGstE',
    appId: '1:558386649713:ios:fc5216ae9645d3ac51d9d0',
    messagingSenderId: '558386649713',
    projectId: 'flutter-fb-auth-4fdc1',
    storageBucket: 'flutter-fb-auth-4fdc1.appspot.com',
    iosBundleId: 'com.example.flutterAuthTut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYZRYEFfk34PxQ_rCj5gW8MPIRRWjGstE',
    appId: '1:558386649713:ios:fc5216ae9645d3ac51d9d0',
    messagingSenderId: '558386649713',
    projectId: 'flutter-fb-auth-4fdc1',
    storageBucket: 'flutter-fb-auth-4fdc1.appspot.com',
    iosBundleId: 'com.example.flutterAuthTut',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdETmIU8BGxjUMvveAkXErVSWXLP1AEwQ',
    appId: '1:558386649713:web:28be4449168af03a51d9d0',
    messagingSenderId: '558386649713',
    projectId: 'flutter-fb-auth-4fdc1',
    authDomain: 'flutter-fb-auth-4fdc1.firebaseapp.com',
    storageBucket: 'flutter-fb-auth-4fdc1.appspot.com',
  );
}
